# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a0f95f121a69ea30aeeb7b0fee3c9fd64987bb29d389ea2ffd25f9bd8c7597f7043f2e374f56c81c2fc907a48e1b9568fead296a5f811a3fe24da6884af40d2
  admin_user: admin
  admin_pass: pass
  mail:
    name: <%= ENV['MAIL_NAME'] %>
    password: <%= ENV['MAIL_PASS'] %>

test:
  secret_key_base: 00865409f7a6e69f62e79f80d49d5c3bebfb7e98239e59eeb97e199debd40dd93f64d7ca31d5e74ca0843c9499c496744558b87c4055a562f35b4c85962a4dfb
  mail:
    name: from@example.com
    password: foobar

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin_user: <%= ENV['ADMIN_USER'] %>
  admin_pass: <%= ENV['ADMIN_PASS'] %>
