require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AdvisoriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Advisory. As you add validations to Advisory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdvisoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET index' do
    it 'assigns all advisories as @advisories' do
      advisory = Advisory.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:advisories)).to eq([advisory])
    end
  end

  describe 'GET show' do
    it 'assigns the requested advisory as @advisory' do
      advisory = Advisory.create! valid_attributes
      get :show, { id: advisory.to_param }, valid_session
      expect(assigns(:advisory)).to eq(advisory)
    end
  end

  describe 'GET new' do
    it 'assigns a new advisory as @advisory' do
      get :new, {}, valid_session
      expect(assigns(:advisory)).to be_a_new(Advisory)
    end
  end

  describe 'GET edit' do
    it 'assigns the requested advisory as @advisory' do
      advisory = Advisory.create! valid_attributes
      get :edit, { id: advisory.to_param }, valid_session
      expect(assigns(:advisory)).to eq(advisory)
    end
  end

  describe 'POST create' do
    describe 'with valid params' do
      it 'creates a new Advisory' do
        expect do
          post :create, { advisory: valid_attributes }, valid_session
        end.to change(Advisory, :count).by(1)
      end

      it 'assigns a newly created advisory as @advisory' do
        post :create, { advisory: valid_attributes }, valid_session
        expect(assigns(:advisory)).to be_a(Advisory)
        expect(assigns(:advisory)).to be_persisted
      end

      it 'redirects to the created advisory' do
        post :create, { advisory: valid_attributes }, valid_session
        expect(response).to redirect_to(Advisory.last)
      end
    end

    describe 'with invalid params' do
      it 'assigns a newly created but unsaved advisory as @advisory' do
        post :create, { advisory: invalid_attributes }, valid_session
        expect(assigns(:advisory)).to be_a_new(Advisory)
      end

      it "re-renders the 'new' template" do
        post :create, { advisory: invalid_attributes }, valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT update' do
    describe 'with valid params' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested advisory' do
        advisory = Advisory.create! valid_attributes
        put :update, { id: advisory.to_param, advisory: new_attributes }, valid_session
        advisory.reload
        skip('Add assertions for updated state')
      end

      it 'assigns the requested advisory as @advisory' do
        advisory = Advisory.create! valid_attributes
        put :update, { id: advisory.to_param, advisory: valid_attributes }, valid_session
        expect(assigns(:advisory)).to eq(advisory)
      end

      it 'redirects to the advisory' do
        advisory = Advisory.create! valid_attributes
        put :update, { id: advisory.to_param, advisory: valid_attributes }, valid_session
        expect(response).to redirect_to(advisory)
      end
    end

    describe 'with invalid params' do
      it 'assigns the advisory as @advisory' do
        advisory = Advisory.create! valid_attributes
        put :update, { id: advisory.to_param, advisory: invalid_attributes }, valid_session
        expect(assigns(:advisory)).to eq(advisory)
      end

      it "re-renders the 'edit' template" do
        advisory = Advisory.create! valid_attributes
        put :update, { id: advisory.to_param, advisory: invalid_attributes }, valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE destroy' do
    it 'destroys the requested advisory' do
      advisory = Advisory.create! valid_attributes
      expect do
        delete :destroy, { id: advisory.to_param }, valid_session
      end.to change(Advisory, :count).by(-1)
    end

    it 'redirects to the advisories list' do
      advisory = Advisory.create! valid_attributes
      delete :destroy, { id: advisory.to_param }, valid_session
      expect(response).to redirect_to(advisories_url)
    end
  end

end
